name: core
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.9.5

  # This is our modular
  dependencies:
    path: ../../libraries/dependencies
  shared:
    path: ../../common/common

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter: